In [31]:
import numpy as np
import pandas as pd
import random
from numpy.random import randn

In [3]:
#Index Levels
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [5]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [7]:
inside

[1, 2, 3, 1, 2, 3]

In [9]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [33]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [35]:
df

             A         B
G1 1  0.335837  0.371117
   2  0.209007  0.450199
   3 -0.038559  0.779998
G2 1 -0.314549 -0.530826
   2  0.459523 -0.599616
   3  1.618062 -0.830321

In [39]:
df.loc['G1'].loc[1]

A    0.335837
B    0.371117
Name: 1, dtype: float64

In [43]:
df.index.names = ['Groups','Num']

In [45]:
df

                   A         B
Groups Num
G1     1    0.335837  0.371117
       2    0.209007  0.450199
       3   -0.038559  0.779998
G2     1   -0.314549 -0.530826
       2    0.459523 -0.599616
       3    1.618062 -0.830321

In [47]:
df.loc['G2'].loc[2]['B']

np.float64(-0.5996157231753132)

In [49]:
df

                   A         B
Groups Num
G1     1    0.335837  0.371117
       2    0.209007  0.450199
       3   -0.038559  0.779998
G2     1   -0.314549 -0.530826
       2    0.459523 -0.599616
       3    1.618062 -0.830321

In [51]:
df.xs(1,level='Num')

               A         B
Groups
G1      0.335837  0.371117
G2     -0.314549 -0.530826